remote: origin
target-branch: main
helm-extra-args: --timeout 600s
chart-dirs:
  - charts
excluded-charts:
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - library=https://bjw-s.github.io/helm-charts
  - retsamedoc=https://retsamedoc.github.io/helm-charts
  - jetstack=https://charts.jetstack.io
