---
apiVersion: v2
name: romm
description: A beautiful, powerful, self-hosted rom manager and player.
home: https://github.com/retsamedoc/helm-charts/tree/main/charts/romm
icon: https://romm.app/_ipx/q_80/images/blocks/logos/romm.svg
version: 26.9.0
appVersion: 5.2.0
kubeVersion: ">=1.31.0-0"

keywords:
  - romm
  - rom-manager

sources:
  - https://github.com/rommapp/romm
  - https://github.com/retsamedoc/helm-charts/tree/main/charts/romm

maintainers:
  - name: retsamedoc
    email: retsamedoc@digitalactionsproject.org

dependencies:
  - name: common
    repository: file://../common
    version: 26.9.0
  - name: mariadb
    version: 20.4.2
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled

annotations:
  catalog.cattle.io/display-name: RomM
  catalog.cattle.io/os: linux
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/retsamedoc/helm-charts/tree/main/charts/romm
    - name: Common library
      url: https://github.com/retsamedoc/helm-charts/tree/main/charts/common
  artifacthub.io/signKey: |
    fingerprint: 40D16531ADC81528315B65664C77EFEB7F669F40
    url: https://retsamedoc.github.io/helm-charts/pgp-public-key.asc
  artifacthub.io/changes: |-
    - kind: changed
      description: |-
        Migrate to in-repo common 26.9.0 and RomM 5.2.0; optional MariaDB, internal Valkey
