---
apiVersion: v2
name: CHART_NAME
description: TODO — describe DISPLAY_NAME
home: https://github.com/retsamedoc/helm-charts/tree/main/charts/CHART_NAME
version: 26.9.0
appVersion: "0.0.0"
kubeVersion: ">=1.31.0-0"

keywords:
  - CHART_NAME

sources:
  - https://github.com/retsamedoc/helm-charts/tree/main/charts/CHART_NAME

maintainers:
  - name: Zach Schimke
    email: retsamedoc@digitalactionsproject.org

dependencies:
  - name: common
    repository: file://../common
    version: 26.9.0

annotations:
  catalog.cattle.io/display-name: DISPLAY_NAME
  catalog.cattle.io/os: linux
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/retsamedoc/helm-charts/tree/main/charts/CHART_NAME
    - name: Common library
      url: https://github.com/retsamedoc/helm-charts/tree/main/charts/common
  artifacthub.io/signKey: |
    fingerprint: 40D16531ADC81528315B65664C77EFEB7F669F40
    url: https://retsamedoc.github.io/helm-charts/pgp-public-key.asc
  artifacthub.io/changes: |-
    - kind: added
      description: Initial chart
