---
apiVersion: v2
name: CHART_NAME
description: TODO — describe DISPLAY_NAME
home: https://github.com/retsamedoc/helm-charts/tree/main/charts/CHART_NAME
version: 0.1.0
appVersion: "0.0.0"
kubeVersion: ">=1.25.0-0"

keywords:
  - CHART_NAME

sources:
  - https://github.com/retsamedoc/helm-charts/tree/main/charts/CHART_NAME

maintainers:
  - name: Zach Schimke
    email: retsamedoc@digitalactionsproject.org

dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2

annotations:
  catalog.cattle.io/display-name: DISPLAY_NAME
  catalog.cattle.io/os: linux
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/retsamedoc/helm-charts/tree/main/charts/CHART_NAME
    - name: Common library chart definition
      url: https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/Chart.yaml
  artifacthub.io/signKey: |
    fingerprint: REPLACE_AFTER_KEY_GENERATION
    url: https://retsamedoc.github.io/helm-charts/pgp-public-key.asc
  artifacthub.io/changes: |-
    - kind: added
      description: Initial chart
