#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository:  briis/weatherflow2mqtt
  # -- image tag
  tag: 3.1.6
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [hass-weatherflow2mqtt repo](https://github.com/briis/hass-weatherflow2mqtt).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: "Europe/Copenhagen"
  # -- Set the unit system used
  # Set this to either imperial or metric.
  UNIT_SYSTEM: "metric"
  # -- Set the language for Wind Direction cardinals and other sensors with text strings as state value
  LANGUAGE: "en"
  # -- Override when the wind speed and bearing is updated.
  # Default is 0 (as soon as possible)
  RAPID_WIND_INTERVAL: "0"
  # -- Enable more debug data in the Container Log. 
  DEBUG: "False"
  # -- Set the hight above sea level for where the station is placed. This is used when calculating some of the sensor values and should be the station elevation plus device height above ground.
  # The value has to be in meters (meters = feet * 0.3048).
  ELEVATION: "0"
  # --  Latitude where the Station is located.
  LATITUDE: "00.0000"
  # -- Longitude where the Station is located.
  LONGITUDE: "000.0000"
  # -- All Time Low Sea Level Pressure. 
  # Default is 960 (Mb for Metric) or Default is 28.35 (inHG for Imperial) 
  ZAMBRETTI_MIN_PRESSURE: "960"
  # -- All Time High Sea Level Pressure.
  # Default is 1060 (Mb for Metric) or Default is 31.30 (inHG for Imperial)
  ZAMBRETTI_MAX_PRESSURE: "1060"
  # -- Host IP used to connect to the weatherflow device. Only change if you have a goofy network setup
  WF_HOST: "0.0.0.0"
  # -- Port used to connect to the weatherflow device
  WF_PORT: "50222"
  # -- Host name used to connect to the MQTT broker
  MQTT_HOST: ""
  # -- Port used to connect to the MQTT broker
  MQTT_PORT: "1883"
  # -- User name used to connect to the MQTT broker
  MQTT_USERNAME:
  # -- Password used to connect to the MQTT broker
  MQTT_PASSWORD:
  # -- Generate MQTT debugging messages in the log.
  MQTT_DEBUG: "False"
  # -- your Station ID for your WeatherFlow Station.
  STATION_ID:
  # -- our personal access Token to allow retrieval of data. If you don't have the token login with your account and create the token. NOTE You must own a WeatherFlow station to get this token
  STATION_TOKEN:
  # -- retrieve Forecast Data from WeatherFlow. If set to True, STATION_ID and STATION_TOKEN must be filled also. NOTE If this is enabled the component will access the Internet to get the Forecast data.
  ADD_FORECAST: False
  # -- interval in minutes, between updates of the Forecast data.
  # Default value is 30 minutes.
  FORECAST_INTERVAL: "30"

persistence:
  data:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 1Gi
    mountPath: /data
