name: "Collect changes"
description: "Collects and stores changed files/charts"

outputs:
  changesDetected:
    description: "Whether or not changes to charts have been detected"
    value: ${{ steps.filter.outputs.addedOrModified }}
  addedOrModifiedFiles:
    description: "A list of the files changed"
    value: ${{ steps.filter.outputs.addedOrModified_files }}
  addedOrModifiedCharts:
    description: "A list of the charts changed"
    value: ${{ steps.filter-charts.outputs.addedOrModified }}

runs:
  using: "composite"
  steps:
    - name: Collect changed files
      uses: dorny/paths-filter@v3
      id: filter
      with:
        list-files: shell
        filters: |
          addedOrModified:
            - added|modified: charts/**

    - name: Collect changed charts
      if: |
        steps.filter.outputs.addedOrModified == 'true'
      id: filter-charts
      shell: bash
      run: |
        CHARTS=()
        PATHS=(${{ steps.filter.outputs.addedOrModified_files }})
        for CHARTPATH in "${PATHS[@]}"
        do
          IFS='/' read -r -a path_parts <<< "${CHARTPATH}"
          chart_name="${path_parts[1]}"
          # Skip non-chart paths (e.g. charts/README.md)
          if [[ -n "${chart_name}" && -f "charts/${chart_name}/Chart.yaml" ]]; then
            CHARTS+=("${chart_name}")
          fi
        done

        # Remove duplicates
        if [[ ${#CHARTS[@]} -gt 0 ]]; then
          CHARTS=( $(printf "%s\n" "${CHARTS[@]}" | sort -u) )
        fi
        printf "addedOrModified=%s\n" "${CHARTS[*]}" >> $GITHUB_OUTPUT
