#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/jmberesford/retrom-service
  # -- image tag
  # The specific digest is for the `amd64` image, but arm compatible images are also available.
  tag: latest
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  PGTZ: UTC
  # PUID: 
  # PGID: 
  # UMASK: 
  # STGRES_PASSWORD: 
  # POSTGRES_USER:
  # POSTGRES_DB:

# -- Configures service settings for the chart. Normally this does not need to be modified.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 3000
      retrom:
        port: 5101

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
    mountPath: /app/config
  data:
    enabled: false
    mountPath: /app/data
  library:
    enabled: false
    mountPath: /app/library
