---
apiVersion: v2
name: esphome
description: ESPHome is a system to control your ESP8266/ESP32 by simple yet powerful configuration files and control them remotely through Home Automation systems
home: https://github.com/retsamedoc/helm-charts/tree/main/charts/esphome
icon: https://raw.githubusercontent.com/esphome/esphome-docs/v1.16.2/_static/favicon-256x256.png
version: 2026.2.5
appVersion: 2024.3.0
kubeVersion: ">=1.25.0-0"

keywords:
  - esphome
  - home-automation

sources:
  - https://github.com/esphome/esphome

maintainers:
  - name: retsamedoc
    email: retsamedoc@digitalactionsproject.org

dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2

annotations:
  catalog.cattle.io/display-name: ESPHome
  catalog.cattle.io/os: linux
  artifacthub.io/links: |
    - name: Chart Source
      url: https://github.com/retsamedoc/helm-charts
    - name: Common library chart definition
      url: https://github.com/bjw-s-labs/helm-charts/blob/main/charts/library/common/Chart.yaml
  artifacthub.io/signKey: |
    fingerprint: 40D16531ADC81528315B65664C77EFEB7F669F40
    url: https://retsamedoc.github.io/helm-charts/pgp-public-key.asc
  artifacthub.io/changes: |-
    - kind: changed
      description: |-
        Migrate templates/values to bjw-s common 4.x controllers API; chart hygiene
