#
# NOTE: This chart inherits from the common library chart.
#

image:
  # -- image repository
  repository: esphome/esphome
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: 2024.3.0

# -- environment variables.
# @default -- See below
env: {}
  # ESPHOME_DASHBOARD_USE_PING: true
  # ESPHOME_DASHBOARD_RELATIVE_URL: "/"
  # ESPHOME_QUICKWIZARD:
  # ESPHOME_IS_HASSIO:
  # DISABLE_HA_AUTHENTICATION:
  # USERNAME:
  # PASSWORD:

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 6052

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
