#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/retsamedoc/helm-charts/blob/main/charts/common/values.yaml
#

controllers:
  main:
    containers:
      main:
        image:
          # -- image repository
          repository: esphome/esphome
          # -- image pull policy
          pullPolicy: IfNotPresent
          # -- image tag
          tag: 2026.8.2

        # -- environment variables.
        # @default -- See below
        env:
          # ICMP status checks. Required when the dashboard is not using host networking (typical on k3s).
          ESPHOME_DASHBOARD_USE_PING: true
          # ESPHOME_DASHBOARD_RELATIVE_URL: "/"
          # USERNAME:
          # PASSWORD:

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    controller: main
    ports:
      http:
        port: 6052

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /config
