name: "Charts: Test"

on:
  workflow_call:
    inputs:
      checkoutCommit:
        required: true
        type: string
      chartChangesDetected:
        required: true
        type: string

jobs:
  generate-install-matrix:
    name: Generate matrix for install
    runs-on: ubuntu-latest
    outputs:
      matrix: |
        {
          "chart": ${{ steps.list-changed.outputs.charts }}
        }
      detected: ${{ steps.list-changed.outputs.detected }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.checkoutCommit }}

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.16.4

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        if: inputs.chartChangesDetected == 'true'
        run: |
          set -euo pipefail
          EXCLUDED=$(yq eval -o=json '.excluded-charts // []' .github/ct-install.yaml)
          CHARTS=$(ct list-changed --config .github/ct-install.yaml)
          if [[ -z "${CHARTS}" ]]; then
            echo "charts=[]" >> "$GITHUB_OUTPUT"
            echo "detected=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          CHARTS_JSON=$(echo "${CHARTS}" | jq -R -s -c 'split("\n")|map(select(length>0))')
          OUTPUT_JSON=$(echo "{\"excluded\": ${EXCLUDED}, \"all\": ${CHARTS_JSON}}" | jq -c '.all-.excluded')
          echo "charts=${OUTPUT_JSON}" >> "$GITHUB_OUTPUT"
          if [[ $(echo "${OUTPUT_JSON}" | jq -c '. | length') -gt 0 ]]; then
            echo "detected=true" >> "$GITHUB_OUTPUT"
          else
            echo "detected=false" >> "$GITHUB_OUTPUT"
          fi

  install-charts:
    needs:
      - generate-install-matrix
    if: needs.generate-install-matrix.outputs.detected == 'true'
    name: Install charts
    strategy:
      matrix: ${{ fromJson(needs.generate-install-matrix.outputs.matrix) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.checkoutCommit }}

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.16.4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Create k3d cluster
        uses: nolar/setup-k3d-k3s@v1
        with:
          version: v1.28

      - name: Remove node taints
        run: |
          kubectl taint --all=true nodes node.cloudprovider.kubernetes.io/uninitialized- || true

      - name: Run chart-testing (install)
        run: ct install --config .github/ct-install.yaml --charts ${{ matrix.chart }}

  install_success:
    needs:
      - generate-install-matrix
      - install-charts
    if: always()
    name: Install successful
    runs-on: ubuntu-latest
    steps:
      - name: Check install matrix status
        if: ${{ (needs.generate-install-matrix.outputs.detected == 'true') && (needs.install-charts.result != 'success') }}
        run: exit 1
